server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: artwork-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/artworks/**

        - id: artist-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/artists/**

        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/notify/**

        - id: sale-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/sales/**


